version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing source dependencies...
      - rm -rf node_modules build
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir dist
      - mv build/* dist
artifacts:
  files:
    - build/**/*
    - package.json
    - package-lock.json
    - node_modules/**/*
